// This file overwrites the default config file generated by the CLI.
const dotenv = require('dotenv');
const path = require('path');
// The secret keys are stored in a separate file.
const secretKeys = require('../../keys.g');
// Some of the config values are stored in the .env file.
dotenv.config({ path: path.join(__dirname, '../../.env') });

module.exports = JSON.stringify({
  port: process.env.PORT,
  host: process.env.HOST,
  mongodb: process.env.MONGO_URL,
  authentication: {
    secret: process.env.SECRET,
    jwtOptions: {
      audience: process.env.AUDIENCE,
      issuer: process.env.ISSUER,
    },
    apiKey: {
      allowed: secretKeys,
    }
  },
});
